# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
r:
  - devel
  - release
  - oldrel
r_packages:
  - covr
after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
